cc_library (
    name = "concepts",
    srcs = [
        "Concept.cpp",
        "BoolConcept.cpp",
        "IntConcept.cpp",
        "FloatConcept.cpp",
        "StringConcept.cpp",
        "ArrayConcept.cpp",
        "StructConcept.cpp",
        "FrameConcept.cpp",
    ],
    deps = [
    ],
)
