cc_library(
    name = "dialog_agents",
    srcs = [
        "DialogAgent.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Agents:agents",
        "//Robot/TCD/FrameTaskDman/DMCore/Grounding:grounding",
    ],
)
