cc_library(
    name = 'query_autocomplete',
    srcs = ['query_autocomplete.cc',],    
    deps = [
            '//Common/Base:Base',
            '//Common/Util/File:simpleLineReader',
            '//Common/ThirdParty/re2:re2',
            '//NLP/WordSegTag/src:wordsegtag', 
           ],
    optimize = ['-std=c++11',],  
)
