cc_binary(name = 'test',
    srcs = ['test.cc'],
    deps = [
           '//Common/Base:Base',
           '//Common/Util/File:simpleLineReader',
           '//Common/Util/File:simpleLineWriter',
           '//Robot/Public/QueryAutoComplete/Src:query_autocomplete',
    ],
    link_all_symbols=True,
)
