thrift_library(
    name = 'ChinaMobileBundle_thrift',
    srcs = ['ChinaMobileBundle.thrift'],
)


thrift_library(
    name = 'ChinaMobile_thrift',
    srcs = [
        'ChinaMobile.thrift'
    ],
    deps = [
        ':ChinaMobileBundle_thrift'
    ],
)
