// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Projects/ChinaMobile/Proto/ChinaMobileCRSServing.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::chinaMobile;

class ChinaMobileCRSServingHandler : virtual public ChinaMobileCRSServingIf {
 public:
  ChinaMobileCRSServingHandler() {
    // Your initialization goes here
  }

  void ChinaMobileCRSProcess( ::chinaMobile::ChinaMobileBundle& _return, const  ::chinaMobile::ChinaMobileBundle& bundle) {
    // Your implementation goes here
    printf("ChinaMobileCRSProcess\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ChinaMobileCRSServingHandler> handler(new ChinaMobileCRSServingHandler());
  shared_ptr<TProcessor> processor(new ChinaMobileCRSServingProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

