/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ChinaMobile_CONSTANTS_H
#define ChinaMobile_CONSTANTS_H

#include "Projects/ChinaMobile/Proto/ChinaMobile_types.h"

namespace chinaMobile {

class ChinaMobileConstants {
 public:
  ChinaMobileConstants();

};

extern const ChinaMobileConstants g_ChinaMobile_constants;

} // namespace

#endif
