/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Projects/ChinaMobile/Proto/ChinaMobile_constants.h"

namespace chinaMobile {

const ChinaMobileConstants g_ChinaMobile_constants;

ChinaMobileConstants::ChinaMobileConstants() {
}

} // namespace

