/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ChinaMobileBundle_CONSTANTS_H
#define ChinaMobileBundle_CONSTANTS_H

#include "Projects/ChinaMobile/Proto/ChinaMobileBundle_types.h"

namespace chinaMobile {

class ChinaMobileBundleConstants {
 public:
  ChinaMobileBundleConstants();

};

extern const ChinaMobileBundleConstants g_ChinaMobileBundle_constants;

} // namespace

#endif
