/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CRSBrainServing_H
#define CRSBrainServing_H

#include <thrift/TDispatchProcessor.h>
#include "Projects/ChinaMobile/Proto/ChinaMobile_types.h"

namespace chinaMobile {

class CRSBrainServingIf {
 public:
  virtual ~CRSBrainServingIf() {}
  virtual void CRSBrainProcess( ::chinaMobile::ChinaMobileBundle& _return, const  ::chinaMobile::ChinaMobileBundle& bundle) = 0;
};

class CRSBrainServingIfFactory {
 public:
  typedef CRSBrainServingIf Handler;

  virtual ~CRSBrainServingIfFactory() {}

  virtual CRSBrainServingIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CRSBrainServingIf* /* handler */) = 0;
};

class CRSBrainServingIfSingletonFactory : virtual public CRSBrainServingIfFactory {
 public:
  CRSBrainServingIfSingletonFactory(const boost::shared_ptr<CRSBrainServingIf>& iface) : iface_(iface) {}
  virtual ~CRSBrainServingIfSingletonFactory() {}

  virtual CRSBrainServingIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CRSBrainServingIf* /* handler */) {}

 protected:
  boost::shared_ptr<CRSBrainServingIf> iface_;
};

class CRSBrainServingNull : virtual public CRSBrainServingIf {
 public:
  virtual ~CRSBrainServingNull() {}
  void CRSBrainProcess( ::chinaMobile::ChinaMobileBundle& /* _return */, const  ::chinaMobile::ChinaMobileBundle& /* bundle */) {
    return;
  }
};

typedef struct _CRSBrainServing_CRSBrainProcess_args__isset {
  _CRSBrainServing_CRSBrainProcess_args__isset() : bundle(false) {}
  bool bundle;
} _CRSBrainServing_CRSBrainProcess_args__isset;

class CRSBrainServing_CRSBrainProcess_args {
 public:

  static const char* ascii_fingerprint; // = "1ECD2695596901A04BE0F391F2074AD3";
  static const uint8_t binary_fingerprint[16]; // = {0x1E,0xCD,0x26,0x95,0x59,0x69,0x01,0xA0,0x4B,0xE0,0xF3,0x91,0xF2,0x07,0x4A,0xD3};

  CRSBrainServing_CRSBrainProcess_args() {
  }

  virtual ~CRSBrainServing_CRSBrainProcess_args() throw() {}

   ::chinaMobile::ChinaMobileBundle bundle;

  _CRSBrainServing_CRSBrainProcess_args__isset __isset;

  void __set_bundle(const  ::chinaMobile::ChinaMobileBundle& val) {
    bundle = val;
  }

  bool operator == (const CRSBrainServing_CRSBrainProcess_args & rhs) const
  {
    if (!(bundle == rhs.bundle))
      return false;
    return true;
  }
  bool operator != (const CRSBrainServing_CRSBrainProcess_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CRSBrainServing_CRSBrainProcess_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CRSBrainServing_CRSBrainProcess_pargs {
 public:

  static const char* ascii_fingerprint; // = "1ECD2695596901A04BE0F391F2074AD3";
  static const uint8_t binary_fingerprint[16]; // = {0x1E,0xCD,0x26,0x95,0x59,0x69,0x01,0xA0,0x4B,0xE0,0xF3,0x91,0xF2,0x07,0x4A,0xD3};


  virtual ~CRSBrainServing_CRSBrainProcess_pargs() throw() {}

  const  ::chinaMobile::ChinaMobileBundle* bundle;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CRSBrainServing_CRSBrainProcess_result__isset {
  _CRSBrainServing_CRSBrainProcess_result__isset() : success(false) {}
  bool success;
} _CRSBrainServing_CRSBrainProcess_result__isset;

class CRSBrainServing_CRSBrainProcess_result {
 public:

  static const char* ascii_fingerprint; // = "0E5E3EFA53952BB870C07E7C5C9C7934";
  static const uint8_t binary_fingerprint[16]; // = {0x0E,0x5E,0x3E,0xFA,0x53,0x95,0x2B,0xB8,0x70,0xC0,0x7E,0x7C,0x5C,0x9C,0x79,0x34};

  CRSBrainServing_CRSBrainProcess_result() {
  }

  virtual ~CRSBrainServing_CRSBrainProcess_result() throw() {}

   ::chinaMobile::ChinaMobileBundle success;

  _CRSBrainServing_CRSBrainProcess_result__isset __isset;

  void __set_success(const  ::chinaMobile::ChinaMobileBundle& val) {
    success = val;
  }

  bool operator == (const CRSBrainServing_CRSBrainProcess_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CRSBrainServing_CRSBrainProcess_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CRSBrainServing_CRSBrainProcess_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CRSBrainServing_CRSBrainProcess_presult__isset {
  _CRSBrainServing_CRSBrainProcess_presult__isset() : success(false) {}
  bool success;
} _CRSBrainServing_CRSBrainProcess_presult__isset;

class CRSBrainServing_CRSBrainProcess_presult {
 public:

  static const char* ascii_fingerprint; // = "0E5E3EFA53952BB870C07E7C5C9C7934";
  static const uint8_t binary_fingerprint[16]; // = {0x0E,0x5E,0x3E,0xFA,0x53,0x95,0x2B,0xB8,0x70,0xC0,0x7E,0x7C,0x5C,0x9C,0x79,0x34};


  virtual ~CRSBrainServing_CRSBrainProcess_presult() throw() {}

   ::chinaMobile::ChinaMobileBundle* success;

  _CRSBrainServing_CRSBrainProcess_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CRSBrainServingClient : virtual public CRSBrainServingIf {
 public:
  CRSBrainServingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  CRSBrainServingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void CRSBrainProcess( ::chinaMobile::ChinaMobileBundle& _return, const  ::chinaMobile::ChinaMobileBundle& bundle);
  void send_CRSBrainProcess(const  ::chinaMobile::ChinaMobileBundle& bundle);
  void recv_CRSBrainProcess( ::chinaMobile::ChinaMobileBundle& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CRSBrainServingProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CRSBrainServingIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CRSBrainServingProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_CRSBrainProcess(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CRSBrainServingProcessor(boost::shared_ptr<CRSBrainServingIf> iface) :
    iface_(iface) {
    processMap_["CRSBrainProcess"] = &CRSBrainServingProcessor::process_CRSBrainProcess;
  }

  virtual ~CRSBrainServingProcessor() {}
};

class CRSBrainServingProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CRSBrainServingProcessorFactory(const ::boost::shared_ptr< CRSBrainServingIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CRSBrainServingIfFactory > handlerFactory_;
};

class CRSBrainServingMultiface : virtual public CRSBrainServingIf {
 public:
  CRSBrainServingMultiface(std::vector<boost::shared_ptr<CRSBrainServingIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CRSBrainServingMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CRSBrainServingIf> > ifaces_;
  CRSBrainServingMultiface() {}
  void add(boost::shared_ptr<CRSBrainServingIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void CRSBrainProcess( ::chinaMobile::ChinaMobileBundle& _return, const  ::chinaMobile::ChinaMobileBundle& bundle) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->CRSBrainProcess(_return, bundle);
    }
    ifaces_[i]->CRSBrainProcess(_return, bundle);
    return;
  }

};

} // namespace

#endif
