cc_library(
    name = "grounding_actions",
    srcs = [
        "GroundingAction.cpp",
        "GAAccept.cpp",
        "GAAskRepeat.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Grounding:grounding_utils",
    ],
)
