cc_library (
    name = "basic_agents",
    srcs = [
        "DialogAgency.cpp",
        "MAExecute.cpp",
        "MARequest.cpp",
        "MAInform.cpp",
        "MAExpect.cpp",
        "MAOperate.cpp",
        "MAGainConcept.cpp",
        "MATaskSkip.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Agents/DialogAgents:dialog_agents",
    ],
)
