cc_library (
    name = "grounding",
    srcs = [
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Grounding/GroundingModels:grounding_models",
        "//Robot/TCD/FrameTaskDman/DMCore/Grounding/GroundingActions:grounding_actions",
    ],
)

cc_library(
    name = "grounding_utils",
    srcs = [
        "GroundingUtils.cpp",
    ],
    deps = [
    ],
)
