cc_library(
    name = "dm_core",
    srcs = [],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Agents:agents",
        "//Robot/TCD/FrameTaskDman/DMCore/Concepts:concepts",
        "//Robot/TCD/FrameTaskDman/DMCore/Grounding:grounding",
        "//Robot/TCD/FrameTaskDman/DMCore/Outputs:outputs",
        "//Robot/TCD/FrameTaskDman/DMCore/Agents/CoreAgents:core_agents",
    ],
    link_all_symbols = True
)
