cc_library (
    name = "agents",
    srcs = [
        "Agent.cpp",
        #"Registry.cpp",
        "RegistryAgent.cpp",
        "RegistryAgentType.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Concepts:concepts",
        #"//Robot/TCD/FrameTaskDman/DMCore/Agents/CoreAgents:core_agents",
        #"//Robot/TCD/FrameTaskDman/DMCore/Agents/DialogAgents:dialog_agents",
    ],
    link_all_symbols = True
)
