cc_library(name = 'userContext',
    srcs = [
        'userContext.cc'
    ],
    deps = [
        '#crypto',
        '//Common/Base:Base',
        '//Robot/Public/Proto:serviceThrift',
        '//Robot/Public/Utils:rewriteQueryHelper',
        '//Common/Util/Encode:encodeUtil',
        '//Common/Util/RedisWrapper:redisPool',
        '//Common/Util/Serialize:base64',
    ],
)

