cc_library(
    name = "frame_task_dman",
    srcs = [],
    deps = [
        "//Common/Base:Base",
        "//Robot/TCD/FrameTaskDman/DMCore:dm_core",
        #"//Robot/TCD/FrameTaskDman/DMCore/Agents/CoreAgents:core_agents",
        #"//Robot/TCD/FrameTaskDman/DMCore/Grounding:grounding",
        #"//Robot/TCD/FrameTaskDman/DMCore/Outputsoutputs",
        "//Robot/TCD/FrameTaskDman/DialogTask:dialog_task",
        "//Robot/TCD/FrameTaskDman/Utils:utils",
    ],
    link_all_symbols = True
)

#cc_binary(
#    name = "test_tree",
#    srcs = [
#        "main.cpp",
#    ],
#    deps = [
#        ":frame_task_dman",
#        #"//Robot/TCD/FrameTaskDman/DMCore/Agents/CoreAgents:core_agents",
#        #"//Robot/TCD/FrameTaskDman/DMCore/Grounding:grounding",
#        #"//Robot/TCD/FrameTaskDman/DMCore/Outputsoutputs",
#        #"//Robot/TCD/FrameTaskDman/DialogTask:dialog_task",
#        #"//Robot/TCD/FrameTaskDman/Utils:utils",
#        #'#crypto',
#        #'//Common/Base:Base',
#    ],
#    optimize = ['O3'],
#    extra_cppflags = ['-fno-omit-frame-pointer', '-Wl,--eh-frame-hdr'],
#)
