cc_library(
  name = 'serviceConfigManager',
  srcs = [
    'serviceConfigManager.cc',
  ],
  deps = [
    '//Robot/Public/Utils:protoBufferLoader',
    '//Robot/Public/Proto:serviceConfigProto',
    '//Robot/Public/Utils:trioFlags',
    '//Robot/Public/Proto:serviceConfigProto',
  ],
)
