cc_library (
    name = "grounding_models",
    srcs = [
        "GMConcept.cpp",
        "GroundingModel.cpp",
        "GMRequestAgent.cpp",
        "AllGroundingModels.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Grounding:grounding_utils",
    ],
)
