namespace cpp robot
namespace py robot.common
enum Domain {
  UNKNOWN     = 0;
  CHAT        = 1;
  MUSIC       = 2;
  WEATHER     = 3;
  NEWS        = 4;
  CONTROL     = 5;
  REMIND      = 6;
  QA          = 7;
  JOKE        = 8;
  CALCULATOR  = 9;
  TIME        = 10;
  SYSPROFILE  = 11;
  SPORT_CONTROL = 12;
  IOT_DEVICE_CONTROL = 13;
  MOVIE_TICKET = 14;
  TAKEOUT_FOOD = 15;
  AUDIO = 16;
  AUDIO_CHILD = 17;
  KB          = 18;
  SHOPPING    = 19;
  VIDEO       = 20;
  INSTRUCTION = 21;
}

enum NEType {
  UNKNOWN = 0;
  PLACE = 1;
  PEOPLE = 2;
  ORGANIZATION = 3;
  RESTAURANT = 4;
  FOOD = 5;
  FILM = 6;
  SONG = 7;
  TV_SERIES = 8;
  IOT_DEVICE = 9;
}
