cc_library(
    name = "dialog_task",
    srcs = [
        "DialogTask.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore:dm_core",
        "//Robot/TCD/FrameTaskDman/DMCore/Agents/DialogAgents/DiscourseAgents:discourse_agents",
        "//Robot/TCD/FrameTaskDman/DialogTask/TaskSpecification:task_specification",
    ],
)
