cc_library(
    name = "discourse_agents",
    srcs = [
        "AllDiscourseAgents.cpp",
        "DAHelp.cpp",
        "DANonUnderstanding.cpp",
        "DARepeat.cpp",
    ],
    deps = [
        "//Robot/TCD/FrameTaskDman/DMCore/Agents/DialogAgents:dialog_agents",
        "//Robot/TCD/FrameTaskDman/DMCore/Agents/DialogAgents/BasicAgents:basic_agents",
    ],
)
